---
###### No variables need to be passed to this playbook ######
#
#  inventory_hostname: This is a built-on variable. You don't need to pass this in.
#  iApps_list: created by 'register:' to story the response
#
# Author: Nathan Pearce
###### https://github.com/npearce/F5-iApps_and_Ansible-playbooks ######

- name: Retrieve a list of iApps installed on F5 BIG-IP
  hosts: bigips
  connection: local
  gather_facts: no
  tasks:

  - name: Query iApp resource via BIG-IP REST API
    uri:
      url: https://{{ inventory_hostname }}/mgmt/tm/cloud/templates/iapp/
      validate_certs: no
      user: admin
      password: admin
      return_content: yes
    register: iapps_list

  - name: Print response
    debug: msg="{{ (iapps_list.content|from_json)["items"] }}"
